name: Deploy Lambda Function with CloudFormation

on:
  push:
    branches:
      - main  # Run this workflow on every push to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '14'

    - name: Install Dependencies
      run: npm install
      working-directory: sample-lambda

    - name: Get working directory name
      id: get-directory-name
      run: echo "LAMBDA_DIR=$(basename sample-lambda)" >> $GITHUB_ENV

    - name: Zip Lambda Function
      run: zip -r $LAMBDA_DIR.zip .
      working-directory: sample-lambda

    - name: Upload Lambda Zip to S3
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: ${{ secrets.AWS_REGION }}
      run: |
        aws s3 cp lambda-function/$LAMBDA_DIR.zip s3://YOUR_S3_BUCKET_NAME/$LAMBDA_DIR.zip

    - name: Deploy CloudFormation Stack
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: ${{ secrets.AWS_REGION }}
      run: |
        aws cloudformation deploy \
          --template-file cloudformation/lambda-template.yml \
          --stack-name my-lambda-stack \
          --parameter-overrides S3BucketName=YOUR_S3_BUCKET_NAME S3Key=$LAMBDA_DIR.zip \
          --capabilities CAPABILITY_NAMED_IAM
